[build]
  command = "flotiq import . b7aaee3ef9b0707c044b30fc55767d62 && gatsby build"
  publish = "public/"

[template.environment]
  GATSBY_FLOTIQ_API_KEY="YOUR FLOTIQ API KEY"
  SNIPCART_API_KEY="YOUR SNIPCART KEY"
  GA_MEASUREMENT_ID="YOUR MEASUREMENT ID"
